repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: GitLeaks
        language: docker_image
        entry: zricethezav/gitleaks:latest
        args: ['detect', '--source', '.', '--verbose', '--exit-code', '1']
        pass_filenames: false

      - id: trufflehog
        name: TruffleHog
        language: docker_image
        entry: trufflesecurity/trufflehog:latest
        args: ['git', 'file://.', '--only-verified', '--fail', '--no-update']
        pass_filenames: false